// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ObjectRelationalABS.ObjectRelational
{
    using System;
    using System.IO;
    using System.Xml;
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Linq;
    using System.Xml.Linq;
    using System.Collections;
    using System.Collections.Generic;
    
    
    #line 1 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class MVCEditView_v1_0 : MVCEditView_v1_0Base
    {
        public virtual string TransformText()
        {
            this.Write(" \r\n");
            
            #line 18 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
   

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 20 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
 
	public string CurrentXmlFile;
	
	ObjectRelationalAbstraction CurrAbs;
	EntitiesType CurrEntities;
	EntityType CurrEntity;
	GeneratorOutputType CurrGeneratorOutput;
	
	public Tuple<string, string>[] GetGeneratorContent(params string[] xmlFileNames)
	{
		List<Tuple<string, string>> result = new List<Tuple<string, string>>();
		foreach(string xmlFileName in xmlFileNames)
		{
			ObjectRelationalAbstraction abs = LoadXml<ObjectRelationalAbstraction>(xmlFileName);
			CurrAbs = abs;
			foreach(EntitiesType entities in abs.Entities)
			{
				CurrEntities = entities;
				foreach(GeneratorOutputType outputType in entities.GeneratorMeta)
				{
					if(outputType.role != GeneratorOutputTypeRole.MVCViews)
						continue;
					CurrGeneratorOutput = outputType;
					foreach(EntityType entity in entities.Entity.Where(ent => ent.ViewGeneration != null))
					{
						if(entity.ViewGeneration == null)
							continue;
						CurrEntity = entity;
						foreach(EditorViewType editorView in entity.ViewGeneration)
						{
							GenerationEnvironment.Clear();
							GenerateEditView(editorView);
							string content = GenerationEnvironment.ToString();
							string fileName = Path.Combine("Views", entity.name, "Edit" + editorView.forType + ".cshtml");
							Tuple<string, string> generation = 
								Tuple.Create(fileName, content);
							result.Add(generation);
						}
					}
				}
			}
		}
		return result.ToArray();
	}
	
	#region Class Level Variable Block
	
	//CQRS_v1_0.DomainType CurrentDomain;
	
	#endregion
	
	string GetTypeWithParentName(string typeName)
	{
		return CurrEntity.name + typeName;
	}
	
	string GetDataClassName(string typeName)
	{
		return "Edit" + typeName + "Data";
	}
	
	string GetContentFieldName(string typeName, bool isCollection)
	{
		if(isCollection)
			return typeName + "List";
		return typeName + "Item";
	}
	
	string GetContentTypeName(string typeName, bool isCollection)
	{
		if(isCollection)
			return "List<" + typeName + ">";
		return typeName;
	}
	
	void GenerateEditView(EditorViewType editorView)
	{
		string typeName = editorView.forType;
		string typeWithParentName = GetTypeWithParentName(editorView.forType);
		string namespaceName = CurrGeneratorOutput.namespaceName;
		string dataClassName = GetDataClassName(typeWithParentName);
		string rootEntityName = CurrEntity.name;
		string displayName = editorView.displayName;
		bool isCollection = editorView.isCollection;
		string contentTypeName = GetContentTypeName(typeName, isCollection);
		string contentFieldName = GetContentFieldName(typeName, isCollection);

        
        #line default
        #line hidden
        
        #line 106 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("@model ");

        
        #line default
        #line hidden
        
        #line 107 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));

        
        #line default
        #line hidden
        
        #line 107 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(".");

        
        #line default
        #line hidden
        
        #line 107 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dataClassName));

        
        #line default
        #line hidden
        
        #line 107 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("\r\n\r\n@{\r\n    ViewBag.Title = \"Edit ");

        
        #line default
        #line hidden
        
        #line 110 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(displayName));

        
        #line default
        #line hidden
        
        #line 110 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("\";\r\n}\r\n\r\n<h2>Edit ");

        
        #line default
        #line hidden
        
        #line 113 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(displayName));

        
        #line default
        #line hidden
        
        #line 113 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(@"</h2>

<script src=""@Url.Content(""~/Scripts/jquery.validate.min.js"")"" type=""text/javascript""></script>
<script src=""@Url.Content(""~/Scripts/jquery.validate.unobtrusive.min.js"")"" type=""text/javascript""></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>");

        
        #line default
        #line hidden
        
        #line 121 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(displayName));

        
        #line default
        #line hidden
        
        #line 121 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("</legend>\r\n        @Html.HiddenFor(model => model.");

        
        #line default
        #line hidden
        
        #line 122 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(rootEntityName));

        
        #line default
        #line hidden
        
        #line 122 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("Id)\r\n        @Html.HiddenFor(model => model.returnViewName)\r\n        <h2>");

        
        #line default
        #line hidden
        
        #line 124 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(displayName));

        
        #line default
        #line hidden
        
        #line 124 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("</h2>\r\n        <p>\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 126 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
 if(isCollection) { 
        
        #line default
        #line hidden
        
        #line 126 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("        @for(int i = 0; i < Model.");

        
        #line default
        #line hidden
        
        #line 127 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(contentFieldName));

        
        #line default
        #line hidden
        
        #line 127 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(".Count; i++) \r\n        {\r\n            <div>\r\n            @Html.EditorFor(x => x.");

        
        #line default
        #line hidden
        
        #line 130 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(contentFieldName));

        
        #line default
        #line hidden
        
        #line 130 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("[i], \"");

        
        #line default
        #line hidden
        
        #line 130 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 130 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("\")\r\n            </div>\r\n        }\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 133 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
 } else { 
        
        #line default
        #line hidden
        
        #line 133 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("\t\t@Html.EditorFor(x => x.");

        
        #line default
        #line hidden
        
        #line 134 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(contentFieldName));

        
        #line default
        #line hidden
        
        #line 134 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(", \"");

        
        #line default
        #line hidden
        
        #line 134 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(typeName));

        
        #line default
        #line hidden
        
        #line 134 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write("\")\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 135 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
 } 
        
        #line default
        #line hidden
        
        #line 135 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"
this.Write(@"            <input type=""submit"" name=""button"" value=""Add Measurement"" />
        </p>


        <p>
            <input type=""submit"" name=""button"" value=""Save"" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(""Back to List"", ""Index"")
</div>


");

        
        #line default
        #line hidden
        
        #line 151 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\MVCEditView_v1_0.tt"

	}

        
        #line default
        #line hidden
        
        #line 1 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"
 
	T LoadXml<T>(string xmlFileName) {
		using(FileStream fStream = File.OpenRead(xmlFileName)) {
			XmlSerializer serializer = new XmlSerializer(typeof(T));
			T result = (T) serializer.Deserialize(fStream);
			fStream.Close();
			return result;
		}
	}

	void BeginNamespace(string namespaceName) {
		
        
        #line default
        #line hidden
        
        #line 12 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 12 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"
this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));

        
        #line default
        #line hidden
        
        #line 12 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"
this.Write(" { \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 13 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"
 
	}

	void EndBlock() {
		
        
        #line default
        #line hidden
        
        #line 17 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"
this.Write(" } ");

        
        #line default
        #line hidden
        
        #line 17 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\..\Common\CommonCodeblocks.ttinclude"

	}

		
	static string RemoveScands(string sourceString) {
		return sourceString.Replace('ä', 'a').Replace('Ä', 'A').Replace('å', 'a').Replace('Å', 'A').Replace('ö', 'o').Replace('Ö', 'O');
	}
	
	public class GenerationItem
	{
		public string FileName;
		public string Content;
	}
	

        
        #line default
        #line hidden
        
        #line 1 "C:\GitHub\kallex\private\Demos\ProjectStatusReportingDemo\Abstractions\ObjectRelationalABS\ObjectRelational\ObjectRelational_v1_0.ttinclude"

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd", IsNullable=false)]
public partial class ObjectRelationalAbstraction {
    
    private EntitiesType[] entitiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Entities")]
    public EntitiesType[] Entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class EntitiesType {
    
    private GeneratorOutputType[] generatorMetaField;
    
    private EntityType[] entityField;
    
    private string domainNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("GeneratorOutput", IsNullable=false)]
    public GeneratorOutputType[] GeneratorMeta {
        get {
            return this.generatorMetaField;
        }
        set {
            this.generatorMetaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Entity")]
    public EntityType[] Entity {
        get {
            return this.entityField;
        }
        set {
            this.entityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DomainName {
        get {
            return this.domainNameField;
        }
        set {
            this.domainNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class GeneratorOutputType {
    
    private string outputTypeField;
    
    private string namespaceNameField;
    
    private GeneratorOutputTypeRole roleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputType {
        get {
            return this.outputTypeField;
        }
        set {
            this.outputTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string namespaceName {
        get {
            return this.namespaceNameField;
        }
        set {
            this.namespaceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GeneratorOutputTypeRole role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum GeneratorOutputTypeRole {
    
    /// <remarks/>
    BusinessLogic,
    
    /// <remarks/>
    ServerSideService,
    
    /// <remarks/>
    ClientProxy,
    
    /// <remarks/>
    ClientSideService,
    
    /// <remarks/>
    MVCModelClasses,
    
    /// <remarks/>
    MVCControllerClasses,
    
    /// <remarks/>
    MVCViews,
    
    /// <remarks/>
    Database,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class TargetDefinitionType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string dataTypeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class TargetType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum VariableTypeState {
    
    /// <remarks/>
    underDesign,
    
    /// <remarks/>
    designApproved,
    
    /// <remarks/>
    implemented,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ParametersType {
    
    private VariableType[] parameterField;
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public VariableType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Modification", typeof(ModificationType))]
    [System.Xml.Serialization.XmlElementAttribute("Validation", typeof(ValidationType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class VariableType {
    
    private string nameField;
    
    private string dataTypeField;
    
    private VariableTypeMappingMode mappingModeField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    public VariableType() {
        this.mappingModeField = VariableTypeMappingMode.Native;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(VariableTypeMappingMode.Native)]
    public VariableTypeMappingMode mappingMode {
        get {
            return this.mappingModeField;
        }
        set {
            this.mappingModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum VariableTypeMappingMode {
    
    /// <remarks/>
    Native,
    
    /// <remarks/>
    XML,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ModificationType {
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ValidationType {
    
    private TargetType[] targetField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class RequirementType {
    
    private object itemField;
    
    private string nameField;
    
    private RequirementTypeCategory categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FreeformText", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Performance", typeof(RequirementTypePerformance))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RequirementTypeCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class RequirementTypePerformance {
    
    private long maxMemoryBytesField;
    
    private bool maxMemoryBytesFieldSpecified;
    
    private decimal maxCPUTimeMsField;
    
    private bool maxCPUTimeMsFieldSpecified;
    
    private decimal maxTotalTimeMsField;
    
    private bool maxTotalTimeMsFieldSpecified;
    
    private long maxFileIOCountField;
    
    private bool maxFileIOCountFieldSpecified;
    
    private long maxFileIOBytesField;
    
    private bool maxFileIOBytesFieldSpecified;
    
    private decimal maxFileIOTimeMsField;
    
    private bool maxFileIOTimeMsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxMemoryBytes {
        get {
            return this.maxMemoryBytesField;
        }
        set {
            this.maxMemoryBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxMemoryBytesSpecified {
        get {
            return this.maxMemoryBytesFieldSpecified;
        }
        set {
            this.maxMemoryBytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxCPUTimeMs {
        get {
            return this.maxCPUTimeMsField;
        }
        set {
            this.maxCPUTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxCPUTimeMsSpecified {
        get {
            return this.maxCPUTimeMsFieldSpecified;
        }
        set {
            this.maxCPUTimeMsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxTotalTimeMs {
        get {
            return this.maxTotalTimeMsField;
        }
        set {
            this.maxTotalTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxTotalTimeMsSpecified {
        get {
            return this.maxTotalTimeMsFieldSpecified;
        }
        set {
            this.maxTotalTimeMsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxFileIOCount {
        get {
            return this.maxFileIOCountField;
        }
        set {
            this.maxFileIOCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOCountSpecified {
        get {
            return this.maxFileIOCountFieldSpecified;
        }
        set {
            this.maxFileIOCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long maxFileIOBytes {
        get {
            return this.maxFileIOBytesField;
        }
        set {
            this.maxFileIOBytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOBytesSpecified {
        get {
            return this.maxFileIOBytesFieldSpecified;
        }
        set {
            this.maxFileIOBytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal maxFileIOTimeMs {
        get {
            return this.maxFileIOTimeMsField;
        }
        set {
            this.maxFileIOTimeMsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxFileIOTimeMsSpecified {
        get {
            return this.maxFileIOTimeMsFieldSpecified;
        }
        set {
            this.maxFileIOTimeMsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum RequirementTypeCategory {
    
    /// <remarks/>
    Customer,
    
    /// <remarks/>
    Architectural,
    
    /// <remarks/>
    Structural,
    
    /// <remarks/>
    Behavioral,
    
    /// <remarks/>
    Functional,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Non-functional")]
    Nonfunctional,
    
    /// <remarks/>
    Performance,
    
    /// <remarks/>
    Design,
    
    /// <remarks/>
    Derived,
    
    /// <remarks/>
    Allocated,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class UseCaseType {
    
    private string nameField;
    
    private string locationUrlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locationUrl {
        get {
            return this.locationUrlField;
        }
        set {
            this.locationUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class OperationSpecType {
    
    private UseCaseType[] useCasesField;
    
    private RequirementType[] requirementsField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("UseCase", IsNullable=false)]
    public UseCaseType[] UseCases {
        get {
            return this.useCasesField;
        }
        set {
            this.useCasesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Requirement", IsNullable=false)]
    public RequirementType[] Requirements {
        get {
            return this.requirementsField;
        }
        set {
            this.requirementsField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class MethodExecuteType {
    
    private TargetType[] parameterField;
    
    private TargetType[] targetField;
    
    private VariableType[] returnValueField;
    
    private string nameField;
    
    private string designDescField;
    
    private VariableTypeState stateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter")]
    public TargetType[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Target")]
    public TargetType[] Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReturnValue")]
    public VariableType[] ReturnValue {
        get {
            return this.returnValueField;
        }
        set {
            this.returnValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string designDesc {
        get {
            return this.designDescField;
        }
        set {
            this.designDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public VariableTypeState state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class ChildEntityType {
    
    private EntityType entityField;
    
    private string nameField;
    
    private ChildEntityTypeMultiplicity multiplicityField;
    
    public ChildEntityType() {
        this.multiplicityField = ChildEntityTypeMultiplicity.Item1;
    }
    
    /// <remarks/>
    public EntityType Entity {
        get {
            return this.entityField;
        }
        set {
            this.entityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ChildEntityTypeMultiplicity.Item1)]
    public ChildEntityTypeMultiplicity multiplicity {
        get {
            return this.multiplicityField;
        }
        set {
            this.multiplicityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class EntityType {
    
    private EditorViewType[] viewGenerationField;
    
    private VariableType[] propertyField;
    
    private ChildEntityType[] childEntityField;
    
    private ValidationType[] propertyChangeValidationField;
    
    private ValidationType[] beforeCommitValidationField;
    
    private object[] associationsField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("EditorView", IsNullable=false)]
    public EditorViewType[] ViewGeneration {
        get {
            return this.viewGenerationField;
        }
        set {
            this.viewGenerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property")]
    public VariableType[] Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChildEntity")]
    public ChildEntityType[] ChildEntity {
        get {
            return this.childEntityField;
        }
        set {
            this.childEntityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyChangeValidation")]
    public ValidationType[] PropertyChangeValidation {
        get {
            return this.propertyChangeValidationField;
        }
        set {
            this.propertyChangeValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BeforeCommitValidation")]
    public ValidationType[] BeforeCommitValidation {
        get {
            return this.beforeCommitValidationField;
        }
        set {
            this.beforeCommitValidationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Association", IsNullable=false)]
    public object[] Associations {
        get {
            return this.associationsField;
        }
        set {
            this.associationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public partial class EditorViewType {
    
    private string forTypeField;
    
    private string pathFromRootField;
    
    private bool isCollectionField;
    
    private string displayNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string forType {
        get {
            return this.forTypeField;
        }
        set {
            this.forTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pathFromRoot {
        get {
            return this.pathFromRootField;
        }
        set {
            this.pathFromRootField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isCollection {
        get {
            return this.isCollectionField;
        }
        set {
            this.isCollectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Operation_v1_0.xsd")]
public enum ChildEntityTypeMultiplicity {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0_1")]
    Item0_1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0_n")]
    Item0_n,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1_n")]
    Item1_n,
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class MVCEditView_v1_0Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
