<!--w5WhenDefault -->
<h3>When</h3>
<div class="input">
 <div class="inline-inputs">
  <label>Change the date range?</label>
  <input data-datepicker="datepicker" class="small" type="text" value="01/05/2011" />
  <input class="mini" type="text" value="12:00am" />
  to
  <input data-datepicker="datepicker" class="small" type="text" value="05/08/2011" />
  <input class="mini" type="text" value="11:59pm" />
  <span class="help-block">All times are shown as Eastern European Time (GMT +2:00).</span>
 </div>
</div>
<!--w5WhenDefault -->