<!DOCTYPE html>
<html lang="en">
<!-- default-head.txt -->
<?php include 'default-head.txt' ?><!-- default-head.txt -->

<body data-spy="scroll" data-target=".subnav" data-offset="50">

<!-- default-navbar.txt -->
<?php include'default-navbar.txt' ?><!-- default-navbar.txt -->


<div class="container"><!--the container class sets the width of the container and centers it -->
<section id="gridSystem"><!--keep this ID as it adds a padding of 60px to the container -->
<div class="row show-grid">
<div class="span12" style="height:400px; min-height:400px">Container</div>
</div>
</section>

<!-- default-footer.txt -->
<?php include'default-footer.txt' ?> <!-- default-footer.txt-->
</div><!-- /container -->

<!-- Le javascript -->
<?php include '../default-modules/default-le-javascript.txt' ?><!-- Le javascript -->

</body>
</html>
