<!DOCTYPE html>
<html lang="en">
<!-- default-head.txt -->
<?php include 'default-head.txt' ?><!-- default-head.txt -->

<body data-spy="scroll" data-target=".subnav" data-offset="50">

<!-- default-navbar.txt -->
<?php include'default-navbar.txt' ?><!-- default-navbar.txt -->

<div class="container"><!--the container class sets the width of the container and centers it -->
<section id="gridSystem"><!--keep this ID as it adds a padding of 60px to the container -->
<div class="row"><!-- show-grid is for display in the example only -->
<?php include'../default-modules/default-map.txt' ?>
<?php include'../default-modules/default-result-list.txt' ?>
</div><!-- row -->
</section><!-- section -->
<div class="row-fluid">
<!-- followed -->
<?php include '../default-modules/default-followed.txt' ?><!-- /followed -->

<hr class="soften" id="about">

<!-- explanation -->
<?php include '../default-modules/explanation.txt' ?><!-- /explanation -->

<!-- default-footer.txt -->
<?php include'default-footer.txt' ?><!-- default-footer.txt-->
</div><!-- /container -->

<!--Modals-->
<?php include '../default-modules/default-modals.txt' ?><!--/Modals-->

<!-- Le javascript -->
<?php include '../default-modules/default-le-javascript.txt' ?><!-- Le javascript -->

</body>
</html>