<!DOCTYPE html>
<html lang="en">
<?php include 'modules-custom/head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50" style="background-image:none">

<!-- navbar-navbar-fixed-top -->
<?php include'modules-custom/navbar-fixed-top.txt' ?><!-- /navbar-navbar-fixed-top -->
<!-- subnav-fixed -->
<?php include 'modules-custom/subnav-fixed.txt' ?><!-- /subnav-fixed -->

<!-- container -->	
<div class="container">

<!-- container-fluid -->	
<div class="container-fluid">

<!-- row-fluid -->	
<div class="row-fluid">
<!-- span9 map -->	
<?php include 'modules-custom/map.txt' ?><!-- /span9 map -->	
<!-- span3 result-list -->	
<?php include 'modules-custom/result-list.txt' ?><!-- /span3 result-list -->
</div><!-- /row-fluid -->
<div class="row-fluid">
<!-- followed -->
<?php include 'modules-custom/followed.txt' ?><!-- /followed -->
</div>

</div><!-- /container-fluid -->	

<hr class="soften" id="about">

<!-- explanation -->
<?php include 'modules-custom/explanation.txt' ?><!-- /explanation -->

<!-- Footer -->
<?php include 'modules-custom/footer.txt' ?><!-- /Footer -->

</div><!-- /container -->

<!--Modals-->
<?php include 'modules-custom/modals.txt' ?><!--/Modals-->

<!-- Le javascript -->
<?php include 'modules-custom/le-javascript.txt' ?><!-- Le javascript -->

</body>
</html>
